// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AngstromConfig {
    #[prost(bytes="vec", tag="1")]
    pub bundle_fee: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub unlocked_fee: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub protocol_unlocked_fee: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="4")]
    pub pool_removed: bool,
}
// @@protoc_insertion_point(module)