[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
arb_mainnet = "${ARB_RPC_URL}"


[fmt]
line_length = 80
wrap_comments = true

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }


[[profile.default.fs_permissions]]
access = "read-write"
path = "out"