[package]
name = "tycho-substreams"
version = "0.2.0"
edition = "2021"

[dependencies]
substreams-ethereum = "0.9.9"
substreams = "0.5.22"
prost = "0.11"
hex = "0.4.3"
itertools = "0.12.0"
ethabi = "18.0.0"
num-bigint = "0.4.4"
serde = "1.0.204"
serde_json = "1.0.120"
