name: test evm

on:
  push:
    paths:
      - "evm/**"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd evm
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge format check
        run:  |
              forge --version
              forge fmt --check
        id:   format

      - name: Run Forge tests
        run: |
          cd evm
          forge test -vvv
        id: test
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}