name: Publish Propeller Swap Encoders Python Packages to AWS CodeArtifact

on:
  release:
    types:
      - prereleased
      - released
  workflow_dispatch: { }

permissions:
  id-token: write
  contents: read

jobs:
  publish_propeller_swap_encoders:
    uses: propeller-heads/ci-cd-templates/.github/workflows/release-python-package.yaml@main
    permissions:
      id-token: write
      contents: read
    with:
      package_root: "propeller-swap-encoders"
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      role_to_assume: ${{ secrets.ROLE_TO_ASSUME }}
      aws_region: ${{ secrets.AWS_REGION }}
      domain_owner: ${{ secrets.DOMAIN_OWNER }}
