name: Swap encoders CI

on:
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  tests:
    uses: propeller-heads/tycho-protocol-sdk/.github/workflows/python-tests.yaml@main

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Check out Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Env
      uses: ./.github/actions/setup_env

    - name: Black Formatting
      run: |
        black ./propeller-swap-encoders --check --skip-magic-trailing-comma
